"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";

type Photo = { id: string; name: string; url: string };
const demoPhotos = [
  { id: "demo-1", name: "푸른 바다", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85" },
  { id: "demo-2", name: "숲의 빛", url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=85" },
  { id: "demo-3", name: "여름의 길", url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=85" },
];

export default function Home() {
  const [photos, setPhotos] = useState<Photo[]>(demoPhotos); const [active, setActive] = useState(0); const [playing, setPlaying] = useState(true); const [speed, setSpeed] = useState(1); const [columns, setColumns] = useState(8); const [isFullscreen, setIsFullscreen] = useState(false); const [transitionKey, setTransitionKey] = useState(0); const timer = useRef<ReturnType<typeof setInterval> | null>(null); const stageRef = useRef<HTMLDivElement>(null);
  const rows = 6; const cells = useMemo(() => Array.from({ length: rows * columns }, (_, i) => i), [columns]); const current = photos[active] ?? photos[0]; const next = photos[(active + 1) % photos.length] ?? current;
  useEffect(() => { if (!playing || photos.length < 2) return; timer.current = setInterval(() => { setActive((v) => (v + 1) % photos.length); setTransitionKey((v) => v + 1); }, 5200 / speed); return () => { if (timer.current) clearInterval(timer.current); }; }, [playing, photos.length, speed]);
  useEffect(() => () => { photos.filter((p) => p.id.startsWith("upload-")).forEach((p) => URL.revokeObjectURL(p.url)); }, [photos]);
  function addPhotos(event: ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files ?? []).filter((f) => f.type.startsWith("image/")); if (!files.length) return; const uploaded = files.map((file, i) => ({ id: `upload-${Date.now()}-${i}`, name: file.name, url: URL.createObjectURL(file) })); setPhotos((v) => [...v.filter((p) => !p.id.startsWith("demo-")), ...uploaded]); setActive(0); setTransitionKey((v) => v + 1); event.target.value = ""; }
  async function toggleFullscreen() { if (!document.fullscreenElement) await stageRef.current?.requestFullscreen(); else await document.exitFullscreen(); setIsFullscreen(Boolean(document.fullscreenElement)); }
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">M</span><span>MOSAIC MOTION</span></div><div className="top-actions"><span className="privacy-pill"><i /> 기기에서만 처리</span><button className="icon-button" onClick={toggleFullscreen} aria-label="전체 화면">{isFullscreen ? "↙" : "↗"}</button></div></header>
    <section className="hero-copy"><div><p className="eyebrow">PHOTO SEQUENCE / 01</p><h1>사진이 조각나며<br /><em>다음 장면으로</em> 넘어갑니다.</h1></div><p className="intro">사진을 여러 장 추가하고, 격자 조각이 순서대로 맞춰지는 전환을 감상해보세요.</p></section>
    <section className="workspace"><div ref={stageRef} className="stage-wrap"><div className="stage" key={transitionKey} style={{ "--cols": columns } as React.CSSProperties}><div className="stage-backdrop" style={{ backgroundImage: `url(${current?.url})` }} />{cells.map((cell) => { const x = cell % columns; const y = Math.floor(cell / columns); const delay = ((cell * 0.035) + ((cell * 7) % 13) * 0.012).toFixed(3); return <div key={cell} className="tile" style={{ backgroundImage: `url(${next?.url})`, backgroundPosition: `${(x / (columns - 1)) * 100}% ${(y / (rows - 1)) * 100}%`, animationDelay: `${delay}s` }} />; })}<div className="stage-overlay"><span>{String(active + 1).padStart(2, "0")} / {String(photos.length).padStart(2, "0")}</span><span className="stage-caption">MOSAIC STUDY</span></div></div><button className="play-button" onClick={() => setPlaying((v) => !v)} aria-label={playing ? "일시정지" : "재생"}>{playing ? "Ⅱ" : "▶"}</button><div className="stage-note">조각이 순서대로 맞춰지는 중</div></div>
      <aside className="control-panel"><div className="panel-heading"><span>YOUR SEQUENCE</span><span className="count">{photos.length} PHOTOS</span></div><label className="upload-zone"><input type="file" accept="image/*" multiple onChange={addPhotos} /><span className="upload-icon">＋</span><span>사진 추가하기</span><small>여러 장 선택 가능</small></label><div className="thumb-list">{photos.map((photo, index) => <button className={`thumb ${index === active ? "selected" : ""}`} key={photo.id} onClick={() => { setActive(index); setTransitionKey((v) => v + 1); }}><img src={photo.url} alt={photo.name} /><span>{String(index + 1).padStart(2, "0")}</span></button>)}</div><div className="settings"><div className="setting-row"><span>전환 속도</span><div className="speed-buttons">{[0.6, 1, 1.5].map((value) => <button key={value} className={speed === value ? "active" : ""} onClick={() => setSpeed(value)}>{value === 1 ? "기본" : `${value}×`}</button>)}</div></div><div className="setting-row"><span>격자 밀도</span><select value={columns} onChange={(e) => setColumns(Number(e.target.value))}><option value={6}>6 × 6</option><option value={8}>8 × 6</option><option value={10}>10 × 6</option></select></div></div><p className="tip"><span>✦</span> 사진은 브라우저 안에서만 처리됩니다.</p></aside></section>
    <footer><span>PHOTO MOSAIC MOTION</span><span>터치하여 사진을 바꿔보세요</span><span>2026</span></footer>
  </main>;
}
